import { Header } from "@components";
import "./globals.css";
import type { Metadata } from "next";
// import { Roboto } from "next/font/google";
import { Inter, Roboto_Mono } from "next/font/google";

export const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className=''>
      <body
        className={`${inter.variable} font-sans w-full dark:bg-black dark:text-white`}
      >
        <Header />
        <main>{children}</main>
      
      </body>
    </html>
  );
}
